language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_script:
  - composer install --dev
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --extensions=php --report=summary --standard=PSR2 ./src ./tests
after_script:
  - php ./vendor/bin/coveralls -v
